#!/usr/bin/python3
# -*- coding: utf-8 -*-
 
import pymysql
import pymysql.cursors
import time
from telegram import Bot
user_var = 'words'
user_name = 'dimon'
user_name2 = 'din'
user_mail = 'qwer'
user_password = '123'
user_table = 'exam_users'

chat_id = 642411623 #замените на свое значение, подробнее ниже
bot = Bot("5718308924:AAFDDxwBvSoOXZJHOZICW75RZPLD2pSO668")

def send_random_cat():
    try:
        connection = pymysql.connect(host='localhost',
            user='root',
            password='root',
            db='test_bd',
            port=8889,
            cursorclass=pymysql.cursors.DictCursor)
        print('succ')
        try:
            with connection.cursor() as cursor:
                #cursor.execute("SHOW DATABASES;")
                #print(cursor.fetchall())
                select_all_rows = f"SELECT {user_var}, password FROM {user_table} where name = '{user_name}'"
                per = cursor.execute(select_all_rows)
                results = cursor.fetchall()
                #print('pas = ' + str(results[0]["password"]))
                if results == ():
                    print('Такого пользователя нет')
                elif str(results[0]["password"]) != user_password:
                    print(f"неверный пароль")
                elif results != ():
                    print(f"ваш запрос: {results[0][user_var]}")
                else:
                    print('нет такого')
                #print(results['dimon'])
                #bot.send_message(select_all_rows)
                print('+'*20)
        finally:
            connection.close()


    except Exception as ex:
        print("Connection refused...")
        print(ex)

def main() -> None:
    send_random_cat()
    print('Cat has been sent')
    


if __name__ == "__main__":
    main()